## Tizen SDK configuration
# This is generated by Tizen SDK. Please do not modify by yourself.
# Set sdb environment path
export PATH=$PATH:/Users/teacher/tizen-sdk/tools
## End Tizen SDK configuration

export TERM=xterm-256color
